name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']  # 12.xを削除し、より新しいバージョンを追加
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3      # v2からv3にアップデート

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3    # v1からv3にアップデート
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install        
        run: npm install

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build